const albumConstants = {
  FETCH_ALBUMS_REQUEST: 'FETCH_ALBUMS_REQUEST',
  FETCH_ALBUMS_SUCCEEDED: 'FETCH_ALBUMS_SUCCEEDED',
  FETCH_ALBUMS_FAILED: 'FETCH_ALBUMS_FAILED',

  FETCH_ALBUM_DETAIL_REQUEST: 'FETCH_ALBUM_DETAIL_REQUEST',
  FETCH_ALBUM_DETAIL_SUCCEEDED: 'FETCH_ALBUM_DETAIL_SUCCEEDED',
  FETCH_ALBUM_DETAIL_FAILED: 'FETCH_ALBUM_DETAIL_FAILED',
};

export default albumConstants;
