const albumConstants = {
  FETCH_ALBUMS_REQUEST: 'FETCH_ALBUMS_REQUEST',
  FETCH_ALBUMS_SUCCEEDED: 'FETCH_ALBUMS_SUCCEEDED',
  FETCH_ALBUMS_FAILED: 'FETCH_ALBUMS_FAILED',
};

export default albumConstants;
