const artistConstants = {
  FETCH_ARTIST_DETAIL_REQUEST: 'FETCH_ARTIST_DETAIL_REQUEST',
  FETCH_ARTIST_DETAIL_SUCCEEDED: 'FETCH_ARTIST_DETAIL_SUCCEEDED',
  FETCH_ARTIST_DETAIL_FAILED: 'FETCH_ARTIST_DETAIL_FAILED',

  FETCH_ARTIST_TOP_TRACKS_REQUEST: 'FETCH_ARTIST_TOP_TRACKS_REQUEST',
  FETCH_ARTIST_TOP_TRACKS_SUCCEEDED: 'FETCH_ARTIST_TOP_TRACKS_SUCCEEDED',
  FETCH_ARTIST_TOP_TRACKS_FAILED: 'FETCH_ARTIST_TOP_TRACKS_FAILED',

  FETCH_RELATED_ARTISTS_REQUEST: 'FETCH_RELATED_ARTISTS_REQUEST',
  FETCH_RELATED_ARTISTS_SUCCEEDED: 'FETCH_RELATED_ARTISTS_SUCCEEDED',
  FETCH_RELATED_ARTISTS_FAILED: 'FETCH_RELATED_ARTISTS_FAILED',
};

export default artistConstants;
